# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(max_length=200)),
                ('attributes', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(max_length=50)),
                ('threshold_level', models.CharField(max_length=50)),
                ('signal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoenix.Signals')),
            ],
        ),
    ]
