# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
        migrations.RenameModel(
            old_name='Signals',
            new_name='Signal',
        ),
        migrations.RenameModel(
            old_name='Triggers',
            new_name='Trigger',
        ),
    ]
