# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0004_trigger_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='signal',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
