# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0005_auto_20170511_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='rules',
        ),
        migrations.AddField(
            model_name='trigger',
            name='rules',
            field=models.ManyToManyField(to='phoenix.Rule'),
        ),
    ]
