# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0012_auto_20170511_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='operation',
            field=models.CharField(choices=[('lt', 'Less Than'), ('lte', 'Less Than Equal To'), ('eq', 'ORDER'), ('gte', 'ORDER'), ('gt', 'ORDER')], default='lt', max_length=10),
        ),
    ]
