# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:22
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0018_auto_20170511_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='attributes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('email', 'User Email'), ('cancelled_order', 'Cancelled Orders'), ('refund_order', 'Refund Orders'), ('order_count', 'Total Orders'), ('margin', 'Margin')], default='email', max_length=53),
        ),
    ]
