# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0019_auto_20170512_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='action_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='phoenix.Action'),
        ),
    ]
