# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0020_auto_20170512_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
