# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0022_auto_20170512_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='Signal',
        ),
        migrations.RenameField(
            model_name='trigger',
            old_name='rules',
            new_name='signals',
        ),
    ]
