# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phoenix', '0023_auto_20170512_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='attributes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('email', 'User Email'), ('cancelled_order', 'Cancelled Orders'), ('refund_order', 'Refund Orders'), ('order_count', 'Total Orders'), ('margin', 'Margin'), ('amount', 'Amount'), ('amount_paid', 'Amount Paid')], default='email', max_length=72),
        ),
    ]
